service:
  name: "ApiService"
  host: 0.0.0.0
  port: 8089

otherService:
  user: "UserService"
  relation: "RelationService"
  favorite: "FavoriteService"
  video: "VideoService"
  comment: "CommentService"

serviceDependency:
  relation: "UserService"
  favorite: "UserService"
  comment: "UserService"
  video:  "UserService"