mysql:
  source:
    driverName: mysql
    host: 10.21.29.203
    port: 3307
    database: wgxTiktok
    username: root
    password: 1477364283
    charset: utf8mb4
  replica1:
    driverName: mysql
    host: 10.21.29.203
    port: 3308
    database: wgxTiktok
    username: root
    password: 1477364283
    charset: utf8mb4
  replica2:
    driverName: mysql
    host: 127.0.0.1
    port: 3308
    database: wgxdouyin
    username: root
    password: 1477364283
    charset: utf8mb4

redis:
  addr: 127.0.0.1
  port: 6379
  password: tiktokRedis
  db: 0 # 数据库编号