server:
  name: "TikTokRabbitMQServer"
  host: 127.0.0.1
  port: 5672
  username: tiktokRMQ
  password: tiktokRMQ
  vhost: tiktokRMQ

consumer:
  favorite:
    queueName: favorite
    autoAck: true
    prefetchCount: 100
  relation:
    queueName: relation
    autoAck: true
    prefetchCount: 100
  user:
    queueName: user
    autoAck: true
    prefetchCount: 100
