services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9002:9000"     # MinIO 对象存储 API
      - "9003:9001"     # MinIO 控制台
    volumes:
      - ./minio-data:/data    # 本地数据目录挂载到容器
    environment:
      MINIO_ROOT_USER: wgxTiktok             # 管理员用户名
      MINIO_ROOT_PASSWORD: wgxTiktok    # 管理员密码
    command: server /data --console-address ":9001"
    restart: always