services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    ports:
      - "3307:3306/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: 1477364283
    volumes:
      - ./mysql-data-master:/var/lib/mysql
      - ./conf/mysql-master.cnf:/etc/mysql/conf.d/my.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/my.cnf && docker-entrypoint.sh mysqld"
    restart: always
    networks:
      - mysql_network

  mysql-replica1:
    image: mysql:8.0
    container_name: mysql-replica1
    ports:
      - "3308:3306/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: 1477364283
    volumes:
      - ./mysql-data-replica1:/var/lib/mysql
      - ./conf/mysql-replica1.cnf:/etc/mysql/conf.d/my.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/my.cnf && docker-entrypoint.sh mysqld"
    restart: always
    networks:
      - mysql_network

  mysql-replica2:
    image: mysql:8.0
    container_name: mysql-replica2
    ports:
      - "3309:3306/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: 1477364283
    volumes:
      - ./mysql-data-replica2:/var/lib/mysql
      - ./conf/mysql-replica2.cnf:/etc/mysql/conf.d/my.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/my.cnf && docker-entrypoint.sh mysqld"
    restart: always
    networks:
      - mysql_network
networks:
  mysql_network:
    driver: bridge
    name: mysql_network